import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "react-hot-toast";
import Header from "@/components/layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body
        className={cn(
          "min-h-screen bg-background antialiased relative flex flex-col bg-slate-100",
          GeistSans.className
        )}
      >
        <Header />
        <Toaster position="top-center" reverseOrder={true} />
        <div className="flex flex-col max-w-5xl w-full mx-auto">{children}</div>
      </body>
    </html>
  );
}
